services:
  erp-app:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/ceu-erp:latest
    ports:
      - "3001:80"
    restart: always
    networks:
      - ceu-network

networks:
  ceu-network:
    external: true
